name: "streamlit CD action"
on:
  push:
    branches:
      - 'develop'
      
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.STREAMLIT_HOST }}
          username: ${{ secret.STREAMLIT_USERNAME }}
          key: ${{ secret.STREAMLIT_SSHKEY }}
          port: 2242
          script: |
            cd ${{ github.event.repository.name }}
            poetry shell
            git checkout develop
            git pull
            
            
    
    
